In [163]:
import math
import copy
import torch
import numpy as np

In [168]:
sample=1-2*torch.rand(5,10)
classes=1-2*torch.rand(2,10)

In [165]:
def cos_cdist(x1 : torch.Tensor, x2 : torch.Tensor, eps : float = 1e-8):
    #Cosine Similarity
    eps = torch.tensor(eps, device=x1.device)
    norms1 = x1.norm(dim=1).unsqueeze_(1).max(eps)
    norms2 = x2.norm(dim=1).unsqueeze_(0).max(eps)
    cdist = x1 @ x2.T
    cdist.div_(norms1).div_(norms2)
    return cdist
def dropdimension(i):
    sample[:,i]=torch.zeros(len(sample))

In [175]:
[(sample*class_).sum(0) for class_ in classes]

[tensor([-0.6893,  0.8005,  0.3373, -0.0500, -1.1712, -0.2175, -0.1003, -0.4059,
         -0.0541, -0.0312]),
 tensor([-0.4649,  1.3121,  0.3699,  0.0100, -1.6126, -0.0235,  0.1989,  0.2521,
         -0.2660, -0.0109])]

In [174]:
meter

tensor([-0.6893,  0.8005,  0.3373, -0.0500, -1.1712, -0.2175, -0.1003, -0.4059,
        -0.0541, -0.0312])

In [170]:
meter0

tensor([[-0.3755,  0.2589,  0.1771, -0.3840, -0.3114, -0.2242, -0.1877,  0.5299,
         -0.0129,  0.0764],
        [-0.0313,  0.2411,  0.2384, -0.1176, -0.1694,  0.4961,  0.3819, -0.3945,
          0.0104,  0.1950],
        [-0.3859,  0.1779, -0.0042,  0.1539, -0.6791, -0.2842, -0.4754,  0.0706,
         -0.0106,  0.2298],
        [ 0.3443,  0.1285, -0.2461, -0.0754, -0.3701,  0.1389, -0.2350, -0.3801,
         -0.0075, -0.3490],
        [-0.2410, -0.0058,  0.1721,  0.3731,  0.3588, -0.3440,  0.4159, -0.2319,
         -0.0334, -0.1835]])

In [161]:
meter0=(sample*classes[0])
meter1=(sample*classes[1])
metrics=meter0-meter1
low=metrics.argmin()
dropdimension(low)

In [162]:
metrics

tensor([[ 0.0000,  0.0788, -0.0894,  0.0349,  0.4658,  1.7087, -0.0846, -0.0278,
          0.0000, -0.0348]])

In [146]:
(sample*classes).sum(1)/sample.norm(dim=1)/classes.norm(dim=1)

tensor([0.2749, 0.1928])

In [147]:
cos_cdist(sample, classes)

tensor([[0.2749, 0.1928]])